server:
  port: 8082

spring:
  application:
    name: service-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
foo: local