server:
  port: 8087

spring:
  application:
    name: service-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-client
    api-b:
      path: /api-b/**
      serviceId: service-server