server:
  port: 8084

spring:
  application:
    name: service-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8081/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000