server:
  port: 8086

spring:
  application:
    name: service-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
feign:
  hystrix:
    enabled: true

